# COMMAND LINE RULES: ./swiftlint rules
# RULES URL: https://github.com/realm/SwiftLint/blob/master/Rules.md
# RULES CONFIG URL: https://github.com/realm/SwiftLint/tree/master/Source/SwiftLintFramework/Rules/RuleConfigurations

disabled_rules: # rule identifiers to exclude from running
    # String enum values can be omitted when they are equal to the enumcase name
    - redundant_string_enum_value

    # Operators should be surrounded by a single whitespace when defining them.
    - operator_whitespace

    # since 0.38.2
    - orphaned_doc_comment # weird false-positives

    # since 0.40.0
    - computed_accessors_order
    
    - syntactic_sugar
    
    # since 0.56.0
    - contrasted_opening_brace

opt_in_rules: # some rules are only opt-in
    # nil coalescing operator is only evaluated if the lhs is nil, coalescing operator with nil as rhs is redundant
    - redundant_nil_coalescing

    # Some methods should not call super
    - prohibited_super_call

    # Some overridden methods should always call super
    - overridden_super_call

    # Implicitly unwrapped optionals should be avoided when possible.
    - implicitly_unwrapped_optional

    # Force unwrapping should be avoided.
    - force_unwrapping

    # Prefer using .first(where:) over .filter { }.first in collections.
    - first_where

    # Prefer to use extension access modifiers
    - extension_access_modifier

    # Prefer checking isEmpty over comparing count to zero.
    - empty_count

    # Closure expressions should have a single space inside each brace.
    - closure_spacing

    # Operators should be surrounded by a single whitespace when they are being used.
    - operator_usage_whitespace

    # Explicitly calling .init() should be avoided.
    - explicit_init

    # Function parameters should be aligned vertically if they're in multiple lines in a method call.
    - vertical_parameter_alignment_on_call

    # Functions and methods parameters should be either on the same line, or one per line.
    - multiline_parameters

    # IBOutlets should be private to avoid leaking UIKit to higher layers.
    - private_outlet
    - private_action

    # Parentheses are not needed when declaring closure arguments.
    - unneeded_parentheses_in_closure_argument

    # Closure parameters should be on the same line as opening brace.
    - closure_parameter_position

    - let_var_whitespace
    - discouraged_direct_init
    - joined_default_parameter
    - contains_over_first_not_nil
    - array_init
    - literal_expression_end_indentation
    - single_test_class
    - sorted_first_last
    - discouraged_optional_boolean

    - modifier_order
    - fallthrough
    - lower_acl_than_parent
    - override_in_extension
    - untyped_error_in_catch

    - empty_string
    - empty_xctest_method
    - convenience_type
    - redundant_set_access_control
    - unavailable_function

    - legacy_multiple
    - reduce_into

    - collection_alignment
    - discouraged_object_literal
    - identical_operands
    - last_where
    - redundant_type_annotation
    - vertical_whitespace_closing_braces
    - vertical_whitespace_opening_braces
    - legacy_random

    #opt-in since 0.28.0
    - toggle_bool

    # opt-in since 0.35.0
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - empty_collection_literal

    # opt-in since 0.36.0
    - contains_over_range_nil_comparison
    - flatmap_over_map_reduce

    # opt-in since 0.38.1
    - enum_case_associated_values_count
    - optional_enum_case_matching
    - prefer_self_type_over_type_of_self

    # opt-in since 0.38.2
    - indentation_width

    # opt-in since 0.39
    #- void_function_in_ternary
    #- return_value_from_void_function
    #- tuple_pattern

    # opt-in since 0.40.0
    - ibinspectable_in_extension
    #- prefer_zero_over_explicit_init
    #- unneeded_notification_center_removal
    
    - direct_return
    - discarded_notification_center_observer
    - discouraged_assert
    # - explicit_enum_raw_value
    - self_binding
    # - trailing_closure
    - unhandled_throwing_task
    - vertical_whitespace_between_cases
    - legacy_objc_type
    
    # opt-in since 0.53.0
    - private_swiftui_state
        
    # opt-in since 0.55.0
    
    # opt-in since 0.58.0
    - async_without_await
        
    # opt-in since 0.59.0
    # - opaque_over_existential
    
analyzer_rules:
    - unused_import
    
    # opt-in since 0.34.0
    - unused_declaration
    
    - typesafe_array_init


# configurations

first_where: error
contains_over_first_not_nil: error
contains_over_filter_count: error
contains_over_filter_is_empty: error
contains_over_range_nil_comparison: error
sorted_first_last: error
reduce_into: error
last_where: error
extension_access_modifier: error
lower_acl_than_parent: error
closure_spacing: error
explicit_init:
    severity: error
private_action: error
convenience_type: error
#vertical_whitespace_opening_braces: error
vertical_whitespace_closing_braces:
    severity: warning
comma: error
duplicate_imports: error
legacy_constructor: error
force_unwrapping: error

function_body_length:
    error: 50

trailing_whitespace:
    ignores_empty_lines: true
    ignores_comments: true

nesting:
    type_level:
        error: 3
        warning: 3

private_outlet:
    allow_private_set: true
    severity: error

line_length:
    warning: 180
    error: 180
    ignores_function_declarations: true
    ignores_urls: true
    ignores_comments: true
    ignores_interpolated_strings: true

identifier_name:
    min_length:
        warning: 1
        error: 1
    max_length:
        warning: 50
        error: 50

type_name:
    max_length:
        warning: 50
        error: 60

file_length:
    warning: 400
    error: 600
    ignore_comment_only_lines: true

indentation_width:
    include_comments: false
    include_multiline_strings: false
    
redundant_discardable_let:
    ignore_swiftui_view_bodies: true

#attributes:
#    always_on_same_line: ["@objc", "@IBAction", "@frozen", "@escaping"]
#    always_on_line_above: ["@available", "@inlinable", "@discardableResult", "@ObservedObject", "@Atomic", "@Published", "@State"]
#    severity: error
